import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import { getServerSession } from 'next-auth';
import Navbar from './components/Navbar';
import { authOptions } from './api/auth/[...nextauth]/route';

export const metadata: Metadata = {
  title: 'Slambook - Save Your Future Ambitions',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getServerSession(authOptions);
  return (
    <html lang="en" data-theme="primary">
      <body>
        <Navbar data={data} />
        {children}
      </body>
    </html>
  );
}
