import type { Metadata } from 'next';
import './globals.css';
import React from 'react';
import Navbar from './components/Navbar';

export const metadata: Metadata = {
  title: 'Slambook - Save Your Future Ambitions',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="primary">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
